import os
from zxcvbn import zxcvbn
from zxcvbn.matching import add_frequency_lists

add_frequency_lists({
    ##### INSERT DICTIONARY WORDS HERE TO IMPROVE BREAKING SPEEDS #####
    'my_list': ['carolina', 'Carolina', 'tarheel', 'Tarheel'],
})

cwdOutput = str(os.getcwd()) + "\output_data.txt"

# Start an output file to write to
file = open(cwdOutput, "w+")

# Write to output file using each line as new password and data about it
# Also using a comma as a delimiter for possible conversion into excel sheet
results1 = zxcvbn('math1001!', user_inputs=['irrelevant', 'irrelevant'])
results2 = zxcvbn('whogoesthere', user_inputs=['irrelevant', 'irrelevant'])
results3 = zxcvbn('1234$$4321', user_inputs=['irrelevant', 'irrelevant'])
results4 = zxcvbn('mater9gator', user_inputs=['irrelevant', 'irrelevant'])
results5 = zxcvbn('cat2lime!', user_inputs=['irrelevant', 'irrelevant'])
results6 = zxcvbn('overthemountain', user_inputs=['irrelevant', 'irrelevant'])
results7 = zxcvbn('hasanA1998', user_inputs=['irrelevant', 'irrelevant'])
results8 = zxcvbn('$industrio', user_inputs=['irrelevant', 'irrelevant'])
results9 = zxcvbn('busyasabee', user_inputs=['irrelevant', 'irrelevant'])
results10 = zxcvbn('LaughingOutLoud', user_inputs=['irrelevant', 'irrelevant'])
results11 = zxcvbn('bark@myd0g', user_inputs=['irrelevant', 'irrelevant'])
results12 = zxcvbn('stranger1!Danger', user_inputs=['irrelevant', 'irrelevant'])
results13 = zxcvbn('Maximum*Overdrive', user_inputs=['irrelevant', 'irrelevant'])
results14 = zxcvbn('tisIurFri3nd', user_inputs=['irrelevant', 'irrelevant'])
results15 = zxcvbn('cptStarDust98', user_inputs=['irrelevant', 'irrelevant'])
results16 = zxcvbn('savedbythebell', user_inputs=['irrelevant', 'irrelevant'])
results17 = zxcvbn('bark@MYdoge', user_inputs=['irrelevant', 'irrelevant'])
results18 = zxcvbn('c0ntr0l$ur$m0n3y', user_inputs=['irrelevant', 'irrelevant'])
results19 = zxcvbn('bigBoyPatrol001', user_inputs=['irrelevant', 'irrelevant'])
results20 = zxcvbn('balloontowerdefense', user_inputs=['irrelevant', 'irrelevant'])
results21 = zxcvbn('730088588UNC', user_inputs=['irrelevant', 'irrelevant'])
results22 = zxcvbn('cntrlovrride', user_inputs=['irrelevant', 'irrelevant'])
results23 = zxcvbn('bigHwasoverhere', user_inputs=['irrelevant', 'irrelevant'])
results24 = zxcvbn('IwishIwastheone', user_inputs=['irrelevant', 'irrelevant'])
results25 = zxcvbn('mind!over!matter', user_inputs=['irrelevant', 'irrelevant'])
results26 = zxcvbn('nasah1998idasa', user_inputs=['irrelevant', 'irrelevant'])
results27 = zxcvbn('iwasbornon1998', user_inputs=['irrelevant', 'irrelevant'])
results28 = zxcvbn('the.small.stuff', user_inputs=['irrelevant', 'irrelevant'])
results29 = zxcvbn('over under across', user_inputs=['irrelevant', 'irrelevant'])
results30 = zxcvbn('haltwhogoesthere', user_inputs=['irrelevant', 'irrelevant'])
results31 = zxcvbn('backtosqaureone', user_inputs=['irrelevant', 'irrelevant'])
results32 = zxcvbn('openedacanofworms', user_inputs=['irrelevant', 'irrelevant'])
results33 = zxcvbn('get.more.carbs', user_inputs=['irrelevant', 'irrelevant'])
results34 = zxcvbn('ice#ice@baby!', user_inputs=['irrelevant', 'irrelevant'])
results35 = zxcvbn('areyougoingnuts?', user_inputs=['irrelevant', 'irrelevant'])
results36 = zxcvbn('JohnSmit123', user_inputs=['irrelevant', 'irrelevant'])
results37 = zxcvbn('asightforsoreeyes', user_inputs=['irrelevant', 'irrelevant'])
results38 = zxcvbn('apieceofcake', user_inputs=['irrelevant', 'irrelevant'])
results39 = zxcvbn('anarmandaleg', user_inputs=['irrelevant', 'irrelevant'])
results40 = zxcvbn('sightforsoreeyes', user_inputs=['irrelevant', 'irrelevant'])
results41 = zxcvbn('beatingaroundthebush', user_inputs=['irrelevant', 'irrelevant'])
results42 = zxcvbn('dontsweatthesmallstuff', user_inputs=['irrelevant', 'irrelevant'])

file.write("Password:," + results1["password"].strip("\n") + "," + "Guesses Log10:," + str(results1['guesses_log10']) + "," + "Score:," + str(results1["score"]) + "," + "uid: ," + str("1") + ",\n")
file.write("Password:," + results2["password"].strip("\n") + "," + "Guesses Log10:," + str(results2['guesses_log10']) + "," + "Score:," + str(results2["score"]) + "," + "uid: ," + str("2") + ",\n")
file.write("Password:," + results3["password"].strip("\n") + "," + "Guesses Log10:," + str(results3['guesses_log10']) + "," + "Score:," + str(results3["score"]) + "," + "uid: ," + str("3") + ",\n")
file.write("Password:," + results4["password"].strip("\n") + "," + "Guesses Log10:," + str(results4['guesses_log10']) + "," + "Score:," + str(results4["score"]) + "," + "uid: ," + str("4") + ",\n")
file.write("Password:," + results5["password"].strip("\n") + "," + "Guesses Log10:," + str(results5['guesses_log10']) + "," + "Score:," + str(results5["score"]) + "," + "uid: ," + str("5") + ",\n")
file.write("Password:," + results6["password"].strip("\n") + "," + "Guesses Log10:," + str(results6['guesses_log10']) + "," + "Score:," + str(results6["score"]) + "," + "uid: ," + str("6") + ",\n")
file.write("Password:," + results7["password"].strip("\n") + "," + "Guesses Log10:," + str(results7['guesses_log10']) + "," + "Score:," + str(results7["score"]) + "," + "uid: ," + str("7") + ",\n")
file.write("Password:," + results8["password"].strip("\n") + "," + "Guesses Log10:," + str(results8['guesses_log10']) + "," + "Score:," + str(results8["score"]) + "," + "uid: ," + str("8") + ",\n")
file.write("Password:," + results9["password"].strip("\n") + "," + "Guesses Log10:," + str(results9['guesses_log10']) + "," + "Score:," + str(results9["score"]) + "," + "uid: ," + str("9") + ",\n")
file.write("Password:," + results10["password"].strip("\n") + "," + "Guesses Log10:," + str(results10['guesses_log10']) + "," + "Score:," + str(results10["score"]) + "," + "uid: ," + str("10") + ",\n")
file.write("Password:," + results11["password"].strip("\n") + "," + "Guesses Log10:," + str(results11['guesses_log10']) + "," + "Score:," + str(results11["score"]) + "," + "uid: ," + str("11") + ",\n")
file.write("Password:," + results12["password"].strip("\n") + "," + "Guesses Log10:," + str(results12['guesses_log10']) + "," + "Score:," + str(results12["score"]) + "," + "uid: ," + str("12") + ",\n")
file.write("Password:," + results13["password"].strip("\n") + "," + "Guesses Log10:," + str(results13['guesses_log10']) + "," + "Score:," + str(results13["score"]) + "," + "uid: ," + str("13") + ",\n")
file.write("Password:," + results14["password"].strip("\n") + "," + "Guesses Log10:," + str(results14['guesses_log10']) + "," + "Score:," + str(results14["score"]) + "," + "uid: ," + str("14") + ",\n")
file.write("Password:," + results15["password"].strip("\n") + "," + "Guesses Log10:," + str(results15['guesses_log10']) + "," + "Score:," + str(results15["score"]) + "," + "uid: ," + str("15") + ",\n")
file.write("Password:," + results16["password"].strip("\n") + "," + "Guesses Log10:," + str(results16['guesses_log10']) + "," + "Score:," + str(results16["score"]) + "," + "uid: ," + str("16") + ",\n")
file.write("Password:," + results17["password"].strip("\n") + "," + "Guesses Log10:," + str(results17['guesses_log10']) + "," + "Score:," + str(results17["score"]) + "," + "uid: ," + str("17") + ",\n")
file.write("Password:," + results18["password"].strip("\n") + "," + "Guesses Log10:," + str(results18['guesses_log10']) + "," + "Score:," + str(results18["score"]) + "," + "uid: ," + str("18") + ",\n")
file.write("Password:," + results19["password"].strip("\n") + "," + "Guesses Log10:," + str(results19['guesses_log10']) + "," + "Score:," + str(results19["score"]) + "," + "uid: ," + str("19") + ",\n")
file.write("Password:," + results20["password"].strip("\n") + "," + "Guesses Log10:," + str(results20['guesses_log10']) + "," + "Score:," + str(results20["score"]) + "," + "uid: ," + str("20") + ",\n")
file.write("Password:," + results21["password"].strip("\n") + "," + "Guesses Log10:," + str(results21['guesses_log10']) + "," + "Score:," + str(results21["score"]) + "," + "uid: ," + str("21") + ",\n")
file.write("Password:," + results22["password"].strip("\n") + "," + "Guesses Log10:," + str(results22['guesses_log10']) + "," + "Score:," + str(results22["score"]) + "," + "uid: ," + str("22") + ",\n")
file.write("Password:," + results23["password"].strip("\n") + "," + "Guesses Log10:," + str(results23['guesses_log10']) + "," + "Score:," + str(results23["score"]) + "," + "uid: ," + str("23") + ",\n")
file.write("Password:," + results24["password"].strip("\n") + "," + "Guesses Log10:," + str(results24['guesses_log10']) + "," + "Score:," + str(results24["score"]) + "," + "uid: ," + str("24") + ",\n")
file.write("Password:," + results25["password"].strip("\n") + "," + "Guesses Log10:," + str(results25['guesses_log10']) + "," + "Score:," + str(results25["score"]) + "," + "uid: ," + str("25") + ",\n")
file.write("Password:," + results26["password"].strip("\n") + "," + "Guesses Log10:," + str(results26['guesses_log10']) + "," + "Score:," + str(results26["score"]) + "," + "uid: ," + str("26") + ",\n")
file.write("Password:," + results27["password"].strip("\n") + "," + "Guesses Log10:," + str(results27['guesses_log10']) + "," + "Score:," + str(results27["score"]) + "," + "uid: ," + str("27") + ",\n")
file.write("Password:," + results28["password"].strip("\n") + "," + "Guesses Log10:," + str(results28['guesses_log10']) + "," + "Score:," + str(results28["score"]) + "," + "uid: ," + str("28") + ",\n")
file.write("Password:," + results29["password"].strip("\n") + "," + "Guesses Log10:," + str(results29['guesses_log10']) + "," + "Score:," + str(results29["score"]) + "," + "uid: ," + str("29") + ",\n")
file.write("Password:," + results30["password"].strip("\n") + "," + "Guesses Log10:," + str(results30['guesses_log10']) + "," + "Score:," + str(results30["score"]) + "," + "uid: ," + str("30") + ",\n")
file.write("Password:," + results31["password"].strip("\n") + "," + "Guesses Log10:," + str(results31['guesses_log10']) + "," + "Score:," + str(results31["score"]) + "," + "uid: ," + str("31") + ",\n")
file.write("Password:," + results32["password"].strip("\n") + "," + "Guesses Log10:," + str(results32['guesses_log10']) + "," + "Score:," + str(results32["score"]) + "," + "uid: ," + str("32") + ",\n")
file.write("Password:," + results33["password"].strip("\n") + "," + "Guesses Log10:," + str(results33['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("33") + ",\n")
file.write("Password:," + results34["password"].strip("\n") + "," + "Guesses Log10:," + str(results34['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("34") + ",\n")
file.write("Password:," + results35["password"].strip("\n") + "," + "Guesses Log10:," + str(results35['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("35") + ",\n")
file.write("Password:," + results36["password"].strip("\n") + "," + "Guesses Log10:," + str(results36['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("36") + ",\n")
file.write("Password:," + results37["password"].strip("\n") + "," + "Guesses Log10:," + str(results37['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("37") + ",\n")
file.write("Password:," + results38["password"].strip("\n") + "," + "Guesses Log10:," + str(results38['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("38") + ",\n")
file.write("Password:," + results39["password"].strip("\n") + "," + "Guesses Log10:," + str(results39['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("39") + ",\n")
file.write("Password:," + results40["password"].strip("\n") + "," + "Guesses Log10:," + str(results40['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("40") + ",\n")
file.write("Password:," + results41["password"].strip("\n") + "," + "Guesses Log10:," + str(results41['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("41") + ",\n")
file.write("Password:," + results42["password"].strip("\n") + "," + "Guesses Log10:," + str(results42['guesses_log10']) + "," + "Score:," + str(results33["score"]) + "," + "uid: ," + str("42") + ",\n")

# Stop using file for good practice
file.close()